# If a player's message contains one of these phrases, do not display it, and inform the sender. One phrase/line.
Disallowed Phrases:
- " c "
- " o "
- " u "
- " r "
- " y "
- " b4 "
- " ur "
- " gr8 "
- " 2day "
- " 4u "
- " ez "
- " no1 "
- " any1 "
- " some1 "
- " sum1 "
- " bcuz "
- " cuz "
- " ppl "
- " sry "
- " plz "